name: CI

on:
  - push
  - pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile: [ rails_6, rails_7 ]
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2


      - name: Bundle
        run: |
          bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
          bundle exec appraisal install

      - name: RSpec
        run: |
          bundle exec appraisal rspec

  # build:
  #   name: Build + Publish
  #   runs-on: ubuntu-latest
  #   needs: rspec

  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Set up Ruby 2.6
  #     uses: actions/setup-ruby@v1
  #     with:
  #       version: 2.6.x

  #   - name: Publish to RubyGems
  #     run: |
  #       mkdir -p $HOME/.gem
  #       touch $HOME/.gem/credentials
  #       chmod 0600 $HOME/.gem/credentials
  #       printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
  #       gem build *.gemspec
  #       gem push *.gem
  #     env:
  #       GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
